image: jdrouet/docker-with-buildx:stable

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

build:
    stage: build
    script:
        - export
        - docker version
        - docker buildx create --use
        - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag nolim1t/lnd-unlock:gl-$DOCKER_ENV_CI_COMMIT_REF_SLUG . 

