image: debian:buster-slim

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

before_script:
    - apt update && apt install -y docker.io curl qemu-user-static
    - curl -L --output /docker-buildx "https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64"
    - chmod a+x /docker-buildx
    - cp /docker-buildx /usr/lib/docker/cli-plugins/docker-buildx
    - echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - systemctl restart docker
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use

build:
    stage: build
    script:
        - docker buildx build --platform linux/arm64/v8,linux/amd64 --tag $CI_REGISTRY_IMAGE:$DOCKER_ENV_CI_COMMIT_REF_SLUG . 

